version: '3'

services:

  app:
    container_name: app
    build:
        context: ./app
        dockerfile: Dockerfile
    volumes:
        - ./app:/app
    ports:
        - 5000:5000
    restart: unless-stopped
    environment:
        PORT: 5000
        MYSQL_PORT: 3306
    env_file: ./.secret.env
    depends_on:
        - mysql
    links:
        - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0.18
    ports:
      - 32000:3306
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    env_file: ./.secret.env